### ISSUE TITLE
Messages total - Could not locate that visualization

### ISSUE THREAD

**Issue by mark-rodgers** [ActionScripted/elastic-kibana-postfix#3]
Wow, this is awesome. Exactly what I was looking for. I did hover notice one issue with the "Messages total" visualization. If you have any ideas on how I can fix this let me know, thanks!

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2798202/55096967-23e4b700-5078-11e9-8f11-8989e01cce7b.png">

**Comment by ActionScripted** [comment]
Glad you found this useful!

Unfortunately when it comes to Elastic stack issues, it can be super hard to troubleshoot without direct access to things. I've seen a few issues where removing everything and reinstalling fixed it, but I don't think we need to get so drastic since it's just one missing/invalid visualization.

Let's edit/create this single visualization:
- Go to Visualize and search for "Messages total [Filebeat Postfix]"
- Create/Edit visualization
- Create/Set cardinality (count of unique values) aggregation using "postfix_queueid" with a label of "Total" and with colors and the rest based on the JSON-ish object from this repo (_see below_).
- Save visualization

JSON-ish representation of the visualization from https://github.com/ActionScripted/elastic-kibana-postfix/blob/master/kibana/ui-visualizations.json#L59 :

```
{
  "title":"Messages total [Filebeat Postfix]",
    "type":"metric",
    "params":{
      "addTooltip":true,
      "addLegend":false,
      "type":"metric",
      "metric":{
        "percentageMode":false,
        "useRanges":false,
        "colorSchema":"Green to Red",
        "metricColorMode":"None",
        "colorsRange":[{
          "from":0,
          "to":10000
        }],
        "labels":{
          "show":true
        },
        "invertColors":false,
        "style":{
          "bgFill":"#000",
          "bgColor":false,
          "labelColor":false,
          "subText":"",
          "fontSize":42
        }
      }
    },
    "aggs":[{
      "id":"1",
      "enabled":true,
      "type":"cardinality",
      "schema":"metric",
      "params":{
        "field":"postfix_queueid",
        "customLabel":"Total"
      }
    }]
}
```

Now edit the Postfix dashboard and replace the missing visualization with this new/updated one. If it doesn't work or doesn't seem quite right you may need to adjust the visualization a bit and/or double-check settings.

Thankfully of all the visualizations on the dashboard to rebuild, this is the easiest one. :D

**Comment by mark-rodgers** [comment]
Ahh, maybe that's my problem! For some reason that visualization does not exist.

<img width="1076" alt="Screen Shot 2019-03-27 at 12 31 09 PM" src="https://user-images.githubusercontent.com/2798202/55106460-3bc63600-508c-11e9-89db-3ccd9c30bf8c.png">

When I try to create a new metric visualization with a unique count aggregation none of the postfix fields are available 🤔 

<img width="1477" alt="image" src="https://user-images.githubusercontent.com/2798202/55106871-30273f00-508d-11e9-96ee-7ec5e47d870e.png">

**Comment by mark-rodgers** [comment]
Looking at the discover view, the fields are definitely there, not sure why the visualizer is not allowing me to target the postfix_ fields

<img width="419" alt="image" src="https://user-images.githubusercontent.com/2798202/55107369-5ef1e500-508e-11e9-9859-80f94dcfce5d.png">

**Comment by mark-rodgers** [comment]
Apologies! My postfix dat wasn’t being indexed, thanks!

**Comment by ActionScripted** [comment]
Glad you were able to get it working and really appreciate you following up with screenshots and the fix/resolution!

**Comment by li-adrienloiseau** [comment]
Hello,
Someone can post his functional elk stack (with docker-compose) ?
Thanks in advance

**Comment by ActionScripted** [comment]
@li-adrienloiseau: I don’t have one I can share, but there’s an official example setup here: https://github.com/elastic/stack-docker

You could use that as a starter and run the setup of this repo on top.
